config/routes.rb
Rails.application.routes.draw do
  get 'invites/new'

  root 'sessions#new'

  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :invites
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :attendees, through: :invites

  def self.upcoming
    where("time > ?", DateTime.now)
  end

  def self.past
    where("time < ?", DateTime.now)
  end
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :attendee, class_name: 'User', foreign_key: "attendee_id"
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: "creator_id"
  has_many :invites, foreign_key: "attendee_id"
  has_many :attended_events, through: :invites, source: :event  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :login_check, only: [:new,:create]
  def show
    @event = Event.find(params[:id])    
  end

  def index
    @events = Event.all
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to @event
    else
      redirect_to new
    end
  end

  private

    def event_params
      params.require(:event).permit(:name, :location, :time)
    end

    def login_check
      redirect_to root_path unless logged_in?
    end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def new
    @invite = Invite.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user
      session[:user_id] = user.id
      redirect_to user
    else
      redirect_to root_path
    end
  end

  def destroy
    if session[:user_id]
      log_out
      redirect_to root_path
    end
  end

  private

  def session_params
    params.require(:session).permit(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:username, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @user ||= User.find(session[:user_id])
  end

  def log_out
    @user = nil
    session[:user_id] = nil
  end

  def logged_in?
    session[:user_id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<ul>
  <li><strong>Name:</strong> <%= event.name %></li>
  <li><strong>Location:</strong> <%= event.location %></li>
  <li><strong>Time:</strong> <%= event.time %></li>
  <li class="creator"><strong>Creator:</strong> <%= event.creator.username %></li>  
</ul>

app/views/events/index.html.erb
<h2>Upcoming Events</h2>
<%= render @events.upcoming %>

<h2>Past Events</h2>
<%= render @events.past %>

app/views/events/new.html.erb
<h1>Create event</h1>
<%= form_for @event do |f| %>
  <%= f.label :name, "Event's Name:" %>
  <%= f.text_field :name %></br>
  <%= f.label :location, "Location:" %>
  <%= f.text_field :location %></br>
  <%= f.datetime_local_field :time %></br>
  <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= render @event %>
<div="guest-list">
  <strong>Attendees:</strong>
  <ul>
    <% if @event.attendees.empty? %>
      <li>None found</li>
    <% else %>
      <% @event.attendees.each do |guest| %>
      <li><%= guest.username %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if session[:user_id] %>
    <%= render 'shared/header' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav>
  <%= link_to "Events Index", events_path %> |
  <%= link_to "My Events", current_user %> |
  <%= link_to "Create Event", new_event_path %>
    <span class="ident">
      Logged in as: <%= current_user.username %>
      <%= link_to "(X)", logout_path, method: :delete %>
    </span>
</nav>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Create user</h1>
<%= form_for @user do |f| %>
  <%= f.label :username, "Username:" %>
  <%= f.text_field :username %></br>
  <%= f.label :email, "Email:" %>
  <%= f.text_field :email %></br>
  <%= f.submit "Create" %>
<% end %>

app/views/users/show.html.erb
<h1>User: <%= @user.username %></h1>
<h3>Email address: <%= @user.email%> </h3>
</br>

<h2>Events created:</h2>
<div class="user-events">
  <% if @user.events.empty? %>
    <ul>
      <li><strong>No events found!</strong></li>
    </ul>
  <% else %>
    <%= render @user.events %>
  <% end %>
</div>

<h2>Upcoming Events Attending:</h2>
<div class="attended-events">
  <% if @user.attended_events.upcoming.empty? %>
    <ul>
      <li><strong>No events found!</strong></li>
    </ul>
  <% else %>
    <%= render @user.attended_events.upcoming %>
  <% end %>
</div>

<h2>Past Events Attended:</h2>
<div class="attended-events">
  <% if @user.attended_events.past.empty? %>
    <ul>
      <li><strong>No events found!</strong></li>
    </ul>
  <% else %>
    <%= render @user.attended_events.past %>
  <% end %>
</div>